import type { LangCode } from './types';

// Translations, keyed by the English source string (see types.ts). English is the source
// language and needs no entry — a missing key (or missing language) falls back to the English
// text, so the UI is always readable while translation is in progress.
//
// Structure is key-major: each English string lists all its translations together, so wiring a
// new component means adding one block per new string with every language in one place. Order of
// languages within a block: es zh ja de ru it fr pt ko ar hi.

type Translations = Partial<Record<LangCode, string>>;

const T: Record<string, Translations> = {
  // ---- App shell: navigation, landing, login box ----
  'My area': { es: 'Mi área', zh: '我的区域', ja: 'マイエリア', de: 'Mein Bereich', ru: 'Мой раздел', it: 'La mia area', fr: 'Mon espace', pt: 'Minha área', ko: '내 영역', ar: 'منطقتي', hi: 'मेरा क्षेत्र' },
  'DAO Member overview': { es: 'Resumen de miembros de la DAO', zh: 'DAO 成员概览', ja: 'DAO メンバー概要', de: 'DAO-Mitgliederübersicht', ru: 'Обзор участников DAO', it: 'Panoramica membri della DAO', fr: 'Aperçu des membres de la DAO', pt: 'Visão geral dos membros da DAO', ko: 'DAO 회원 개요', ar: 'نظرة عامة على أعضاء DAO', hi: 'DAO सदस्य अवलोकन' },
  'DAO members': { es: 'Miembros de la DAO', zh: 'DAO 成员', ja: 'DAO メンバー', de: 'DAO-Mitglieder', ru: 'Участники DAO', it: 'Membri della DAO', fr: 'Membres de la DAO', pt: 'Membros da DAO', ko: 'DAO 회원', ar: 'أعضاء DAO', hi: 'DAO सदस्य' },
  Submitters: { es: 'Proponentes', zh: '提交者', ja: '提出者', de: 'Einreicher', ru: 'Заявители', it: 'Proponenti', fr: 'Soumetteurs', pt: 'Proponentes', ko: '제출자', ar: 'مقدمو الطلبات', hi: 'प्रस्तुतकर्ता' },
  Experts: { es: 'Expertos', zh: '专家', ja: '専門家', de: 'Experten', ru: 'Эксперты', it: 'Esperti', fr: 'Experts', pt: 'Especialistas', ko: '전문가', ar: 'الخبراء', hi: 'विशेषज्ञ' },
  Rounds: { es: 'Rondas', zh: '轮次', ja: 'ラウンド', de: 'Runden', ru: 'Раунды', it: 'Round', fr: 'Tours', pt: 'Rodadas', ko: '라운드', ar: 'الجولات', hi: 'राउंड' },
  'Funding proposals': { es: 'Propuestas de financiación', zh: '资助提案', ja: '資金提案', de: 'Förderanträge', ru: 'Заявки на финансирование', it: 'Proposte di finanziamento', fr: 'Propositions de financement', pt: 'Propostas de financiamento', ko: '자금 제안', ar: 'مقترحات التمويل', hi: 'वित्तपोषण प्रस्ताव' },
  'Internal proposals': { es: 'Propuestas internas', zh: '内部提案', ja: '内部提案', de: 'Interne Anträge', ru: 'Внутренние предложения', it: 'Proposte interne', fr: 'Propositions internes', pt: 'Propostas internas', ko: '내부 제안', ar: 'المقترحات الداخلية', hi: 'आंतरिक प्रस्ताव' },
  'On-chain proofs': { es: 'Pruebas on-chain', zh: '链上凭证', ja: 'オンチェーン証明', de: 'On-Chain-Nachweise', ru: 'Ончейн-доказательства', it: 'Prove on-chain', fr: 'Preuves on-chain', pt: 'Provas on-chain', ko: '온체인 증명', ar: 'إثباتات على السلسلة', hi: 'ऑन-चेन प्रमाण' },
  Treasury: { es: 'Tesorería', zh: '金库', ja: 'トレジャリー', de: 'Schatzkammer', ru: 'Казначейство', it: 'Tesoreria', fr: 'Trésorerie', pt: 'Tesouraria', ko: '재무', ar: 'الخزينة', hi: 'कोष' },
  'Platform setup': { es: 'Configuración de la plataforma', zh: '平台设置', ja: 'プラットフォーム設定', de: 'Plattform-Einrichtung', ru: 'Настройка платформы', it: 'Configurazione della piattaforma', fr: 'Configuration de la plateforme', pt: 'Configuração da plataforma', ko: '플랫폼 설정', ar: 'إعداد المنصة', hi: 'प्लेटफ़ॉर्म सेटअप' },
  'Cardano governance platform (Preprod).': { es: 'Plataforma de gobernanza de Cardano (Preprod).', zh: 'Cardano 治理平台（Preprod）。', ja: 'Cardano ガバナンスプラットフォーム（Preprod）。', de: 'Cardano-Governance-Plattform (Preprod).', ru: 'Платформа управления Cardano (Preprod).', it: 'Piattaforma di governance Cardano (Preprod).', fr: 'Plateforme de gouvernance Cardano (Preprod).', pt: 'Plataforma de governança Cardano (Preprod).', ko: 'Cardano 거버넌스 플랫폼 (Preprod).', ar: 'منصة حوكمة Cardano (Preprod).', hi: 'Cardano गवर्नेंस प्लेटफ़ॉर्म (Preprod)।' },
  'View profile': { es: 'Ver perfil', zh: '查看资料', ja: 'プロフィールを見る', de: 'Profil anzeigen', ru: 'Профиль', it: 'Vedi profilo', fr: 'Voir le profil', pt: 'Ver perfil', ko: '프로필 보기', ar: 'عرض الملف الشخصي', hi: 'प्रोफ़ाइल देखें' },
  'Refresh notifications / to-do counts': { es: 'Actualizar notificaciones / tareas pendientes', zh: '刷新通知 / 待办事项', ja: '通知 / タスクを更新', de: 'Benachrichtigungen / Aufgaben aktualisieren', ru: 'Обновить уведомления / задачи', it: 'Aggiorna notifiche / attività', fr: 'Actualiser les notifications / tâches', pt: 'Atualizar notificações / tarefas', ko: '알림 / 할 일 새로고침', ar: 'تحديث الإشعارات / المهام', hi: 'सूचनाएँ / कार्य ताज़ा करें' },
  'Refresh notifications': { es: 'Actualizar notificaciones', zh: '刷新通知', ja: '通知を更新', de: 'Benachrichtigungen aktualisieren', ru: 'Обновить уведомления', it: 'Aggiorna notifiche', fr: 'Actualiser les notifications', pt: 'Atualizar notificações', ko: '알림 새로고침', ar: 'تحديث الإشعارات', hi: 'सूचनाएँ ताज़ा करें' },
  Language: { es: 'Idioma', zh: '语言', ja: '言語', de: 'Sprache', ru: 'Язык', it: 'Lingua', fr: 'Langue', pt: 'Idioma', ko: '언어', ar: 'اللغة', hi: 'भाषा' },
  Theme: { es: 'Tema', zh: '主题', ja: 'テーマ', de: 'Design', ru: 'Тема', it: 'Tema', fr: 'Thème', pt: 'Tema', ko: '테마', ar: 'المظهر', hi: 'थीम' },
  Light: { es: 'Claro', zh: '浅色', ja: 'ライト', de: 'Hell', ru: 'Светлая', it: 'Chiaro', fr: 'Clair', pt: 'Claro', ko: '라이트', ar: 'فاتح', hi: 'लाइट' },
  Dark: { es: 'Oscuro', zh: '深色', ja: 'ダーク', de: 'Dunkel', ru: 'Тёмная', it: 'Scuro', fr: 'Sombre', pt: 'Escuro', ko: '다크', ar: 'داكن', hi: 'डार्क' },

  // ---- My area: tab bar ----
  Profile: { es: 'Perfil', zh: '个人资料', ja: 'プロフィール', de: 'Profil', ru: 'Профиль', it: 'Profilo', fr: 'Profil', pt: 'Perfil', ko: '프로필', ar: 'الملف الشخصي', hi: 'प्रोफ़ाइल' },
  Expert: { es: 'Experto', zh: '专家', ja: '専門家', de: 'Experte', ru: 'Эксперт', it: 'Esperto', fr: 'Expert', pt: 'Especialista', ko: '전문가', ar: 'خبير', hi: 'विशेषज्ञ' },
  'Get started': { es: 'Comenzar', zh: '开始', ja: 'はじめる', de: 'Loslegen', ru: 'Начать', it: 'Inizia', fr: 'Commencer', pt: 'Começar', ko: '시작하기', ar: 'ابدأ', hi: 'शुरू करें' },
  'Voting & reviews': { es: 'Votaciones y revisiones', zh: '投票与评审', ja: '投票とレビュー', de: 'Abstimmungen & Prüfungen', ru: 'Голосования и обзоры', it: 'Votazioni e revisioni', fr: 'Votes et évaluations', pt: 'Votações e avaliações', ko: '투표 및 검토', ar: 'التصويت والمراجعات', hi: 'मतदान और समीक्षाएँ' },
  'My proposals': { es: 'Mis propuestas', zh: '我的提案', ja: '私の提案', de: 'Meine Anträge', ru: 'Мои предложения', it: 'Le mie proposte', fr: 'Mes propositions', pt: 'Minhas propostas', ko: '내 제안', ar: 'مقترحاتي', hi: 'मेरे प्रस्ताव' },
  Messages: { es: 'Mensajes', zh: '消息', ja: 'メッセージ', de: 'Nachrichten', ru: 'Сообщения', it: 'Messaggi', fr: 'Messages', pt: 'Mensagens', ko: '메시지', ar: 'الرسائل', hi: 'संदेश' },
  Actions: { es: 'Acciones', zh: '操作', ja: 'アクション', de: 'Aktionen', ru: 'Действия', it: 'Azioni', fr: 'Actions', pt: 'Ações', ko: '작업', ar: 'الإجراءات', hi: 'कार्रवाइयाँ' },
  'Round control': { es: 'Control de rondas', zh: '轮次控制', ja: 'ラウンド管理', de: 'Rundensteuerung', ru: 'Управление раундом', it: 'Controllo round', fr: 'Contrôle des tours', pt: 'Controle de rodadas', ko: '라운드 제어', ar: 'التحكم في الجولة', hi: 'राउंड नियंत्रण' },
  Rewards: { es: 'Recompensas', zh: '奖励', ja: '報酬', de: 'Belohnungen', ru: 'Награды', it: 'Ricompense', fr: 'Récompenses', pt: 'Recompensas', ko: '보상', ar: 'المكافآت', hi: 'पुरस्कार' },
  Applications: { es: 'Solicitudes', zh: '申请', ja: '申請', de: 'Bewerbungen', ru: 'Заявки', it: 'Candidature', fr: 'Candidatures', pt: 'Inscrições', ko: '신청', ar: 'الطلبات', hi: 'आवेदन' },

  // ---- Treasury tab ----
  Overview: { es: 'Resumen', zh: '概览', ja: '概要', de: 'Übersicht', ru: 'Обзор', it: 'Panoramica', fr: 'Aperçu', pt: 'Visão geral', ko: '개요', ar: 'نظرة عامة', hi: 'अवलोकन' },
  Transactions: { es: 'Transacciones', zh: '交易', ja: 'トランザクション', de: 'Transaktionen', ru: 'Транзакции', it: 'Transazioni', fr: 'Transactions', pt: 'Transações', ko: '거래', ar: 'المعاملات', hi: 'लेन-देन' },
  'Treasury multisig setup': { es: 'Configuración del multisig de tesorería', zh: '金库多签设置', ja: 'トレジャリーのマルチシグ設定', de: 'Treasury-Multisig-Einrichtung', ru: 'Настройка мультиподписи казначейства', it: 'Configurazione multisig della tesoreria', fr: 'Configuration multisig de la trésorerie', pt: 'Configuração do multisig da tesouraria', ko: '재무 멀티시그 설정', ar: 'إعداد التوقيع المتعدد للخزينة', hi: 'कोष मल्टीसिग सेटअप' },
  "The DAO's 3-of-5 multisig holds the budget; a low-balance hot wallet pays tx fees. Budgets: rewards, operations, and one per funding round.": { es: 'El multisig 3 de 5 de la DAO custodia el presupuesto; una hot wallet con saldo bajo paga las comisiones. Presupuestos: recompensas, operaciones y uno por ronda de financiación.', zh: 'DAO 的 3/5 多签持有预算；一个低余额热钱包支付交易手续费。预算：奖励、运营，以及每个资助轮次一个。', ja: 'DAO の 3-of-5 マルチシグが予算を保有し、低残高のホットウォレットが取引手数料を支払います。予算：報酬、運営、資金ラウンドごとに 1 つ。', de: 'Das 3-von-5-Multisig der DAO hält das Budget; eine Hot Wallet mit niedrigem Guthaben zahlt die Tx-Gebühren. Budgets: Belohnungen, Betrieb und eines pro Förderrunde.', ru: 'Мультиподпись DAO 3 из 5 хранит бюджет; горячий кошелёк с малым балансом оплачивает комиссии. Бюджеты: награды, операции и по одному на раунд финансирования.', it: 'Il multisig 3 su 5 della DAO custodisce il budget; un hot wallet a basso saldo paga le commissioni. Budget: ricompense, operazioni e uno per round di finanziamento.', fr: 'Le multisig 3 sur 5 de la DAO détient le budget ; un hot wallet à faible solde paie les frais de transaction. Budgets : récompenses, opérations et un par tour de financement.', pt: 'O multisig 3 de 5 da DAO guarda o orçamento; uma hot wallet de saldo baixo paga as taxas. Orçamentos: recompensas, operações e um por rodada de financiamento.', ko: 'DAO의 3-of-5 멀티시그가 예산을 보유하며, 잔액이 적은 핫 월렛이 거래 수수료를 지불합니다. 예산: 보상, 운영, 그리고 자금 라운드당 하나.', ar: 'يحتفظ التوقيع المتعدد 3 من 5 الخاص بالـ DAO بالميزانية؛ وتدفع محفظة ساخنة منخفضة الرصيد رسوم المعاملات. الميزانيات: المكافآت والعمليات وواحدة لكل جولة تمويل.', hi: 'DAO का 3-में-से-5 मल्टीसिग बजट रखता है; कम-शेष हॉट वॉलेट लेन-देन शुल्क चुकाता है। बजट: पुरस्कार, संचालन, और प्रत्येक वित्तपोषण राउंड के लिए एक।' },

  // ---- Rounds tab ----
  'Round stage:': { es: 'Etapa de la ronda:', zh: '轮次阶段：', ja: 'ラウンドの段階：', de: 'Rundenphase:', ru: 'Этап раунда:', it: 'Fase del round:', fr: 'Étape du tour :', pt: 'Etapa da rodada:', ko: '라운드 단계:', ar: 'مرحلة الجولة:', hi: 'राउंड चरण:' },
  Proposals: { es: 'Propuestas', zh: '提案', ja: '提案', de: 'Anträge', ru: 'Предложения', it: 'Proposte', fr: 'Propositions', pt: 'Propostas', ko: '제안', ar: 'المقترحات', hi: 'प्रस्ताव' },
  Categories: { es: 'Categorías', zh: '类别', ja: 'カテゴリ', de: 'Kategorien', ru: 'Категории', it: 'Categorie', fr: 'Catégories', pt: 'Categorias', ko: '카테고리', ar: 'الفئات', hi: 'श्रेणियाँ' },
  Tally: { es: 'Recuento', zh: '计票', ja: '集計', de: 'Auszählung', ru: 'Подсчёт', it: 'Conteggio', fr: 'Décompte', pt: 'Apuração', ko: '집계', ar: 'الفرز', hi: 'मतगणना' },
  'Voting Result': { es: 'Resultado de la votación', zh: '投票结果', ja: '投票結果', de: 'Abstimmungsergebnis', ru: 'Результат голосования', it: 'Risultato della votazione', fr: 'Résultat du vote', pt: 'Resultado da votação', ko: '투표 결과', ar: 'نتيجة التصويت', hi: 'मतदान परिणाम' },
  'Schedule and Round Setup': { es: 'Calendario y configuración de la ronda', zh: '日程与轮次设置', ja: 'スケジュールとラウンド設定', de: 'Zeitplan und Rundeneinrichtung', ru: 'Расписание и настройка раунда', it: 'Programma e configurazione del round', fr: 'Calendrier et configuration du tour', pt: 'Cronograma e configuração da rodada', ko: '일정 및 라운드 설정', ar: 'الجدول وإعداد الجولة', hi: 'समय-सारणी और राउंड सेटअप' },

  // ---- Common ----
  'Loading…': { es: 'Cargando…', zh: '加载中…', ja: '読み込み中…', de: 'Wird geladen…', ru: 'Загрузка…', it: 'Caricamento…', fr: 'Chargement…', pt: 'Carregando…', ko: '로딩 중…', ar: 'جارٍ التحميل…', hi: 'लोड हो रहा है…' },
  Round: { es: 'Ronda', zh: '轮次', ja: 'ラウンド', de: 'Runde', ru: 'Раунд', it: 'Round', fr: 'Tour', pt: 'Rodada', ko: '라운드', ar: 'الجولة', hi: 'राउंड' },
  'All rounds': { es: 'Todas las rondas', zh: '所有轮次', ja: 'すべてのラウンド', de: 'Alle Runden', ru: 'Все раунды', it: 'Tutti i round', fr: 'Tous les tours', pt: 'Todas as rodadas', ko: '모든 라운드', ar: 'كل الجولات', hi: 'सभी राउंड' },

  // ---- Funding proposals (list) ----
  'No rounds yet — proposals appear once a round opens.': { es: 'Aún no hay rondas: las propuestas aparecen cuando se abre una ronda.', zh: '暂无轮次——轮次开启后将显示提案。', ja: 'ラウンドはまだありません。ラウンドが開始すると提案が表示されます。', de: 'Noch keine Runden – Anträge erscheinen, sobald eine Runde öffnet.', ru: 'Раундов пока нет — предложения появятся, когда откроется раунд.', it: 'Ancora nessun round: le proposte appaiono quando si apre un round.', fr: "Aucun tour pour l'instant — les propositions apparaissent dès qu'un tour s'ouvre.", pt: 'Ainda não há rodadas — as propostas aparecem quando uma rodada abre.', ko: '아직 라운드가 없습니다 — 라운드가 열리면 제안이 표시됩니다.', ar: 'لا توجد جولات بعد — تظهر المقترحات بمجرد فتح جولة.', hi: 'अभी तक कोई राउंड नहीं — राउंड खुलने पर प्रस्ताव दिखाई देंगे।' },
  'Proposals in the active round. Switch rounds to browse earlier ones.': { es: 'Propuestas de la ronda activa. Cambia de ronda para ver las anteriores.', zh: '当前活跃轮次的提案。切换轮次可浏览较早的提案。', ja: 'アクティブなラウンドの提案。ラウンドを切り替えると過去の提案を閲覧できます。', de: 'Anträge der aktiven Runde. Wechseln Sie die Runde, um frühere zu sehen.', ru: 'Предложения активного раунда. Переключите раунд, чтобы посмотреть прежние.', it: 'Proposte del round attivo. Cambia round per vedere quelli precedenti.', fr: 'Propositions du tour actif. Changez de tour pour consulter les précédents.', pt: 'Propostas da rodada ativa. Troque de rodada para ver as anteriores.', ko: '활성 라운드의 제안입니다. 이전 항목을 보려면 라운드를 전환하세요.', ar: 'مقترحات الجولة النشطة. بدّل الجولة لتصفح الجولات السابقة.', hi: 'सक्रिय राउंड के प्रस्ताव। पुराने देखने के लिए राउंड बदलें।' },
  'No active round right now — browse proposals from earlier rounds.': { es: 'No hay ninguna ronda activa ahora: explora propuestas de rondas anteriores.', zh: '当前没有活跃轮次——浏览较早轮次的提案。', ja: '現在アクティブなラウンドはありません。過去のラウンドの提案を閲覧できます。', de: 'Derzeit keine aktive Runde – durchsuchen Sie Anträge früherer Runden.', ru: 'Сейчас нет активного раунда — просмотрите предложения прошлых раундов.', it: 'Nessun round attivo al momento: sfoglia le proposte dei round precedenti.', fr: 'Aucun tour actif pour le moment — parcourez les propositions des tours précédents.', pt: 'Nenhuma rodada ativa no momento — navegue pelas propostas de rodadas anteriores.', ko: '현재 활성 라운드가 없습니다 — 이전 라운드의 제안을 살펴보세요.', ar: 'لا توجد جولة نشطة حاليًا — تصفح مقترحات الجولات السابقة.', hi: 'अभी कोई सक्रिय राउंड नहीं — पुराने राउंड के प्रस्ताव देखें।' },

  // ---- Status badges (StatusBadge — round + proposal statuses, shown app-wide) ----
  PENDING: { es: 'PENDIENTE', zh: '待定', ja: '保留中', de: 'AUSSTEHEND', ru: 'ОЖИДАНИЕ', it: 'IN ATTESA', fr: 'EN ATTENTE', pt: 'PENDENTE', ko: '대기 중', ar: 'قيد الانتظار', hi: 'लंबित' },
  ACTIVE: { es: 'ACTIVA', zh: '进行中', ja: 'アクティブ', de: 'AKTIV', ru: 'АКТИВНО', it: 'ATTIVA', fr: 'ACTIF', pt: 'ATIVA', ko: '진행 중', ar: 'نشط', hi: 'सक्रिय' },
  APPROVED: { es: 'APROBADA', zh: '已批准', ja: '承認済み', de: 'GENEHMIGT', ru: 'ОДОБРЕНО', it: 'APPROVATA', fr: 'APPROUVÉ', pt: 'APROVADA', ko: '승인됨', ar: 'تمت الموافقة', hi: 'स्वीकृत' },
  REJECTED: { es: 'RECHAZADA', zh: '已拒绝', ja: '却下', de: 'ABGELEHNT', ru: 'ОТКЛОНЕНО', it: 'RESPINTA', fr: 'REJETÉ', pt: 'REJEITADA', ko: '거부됨', ar: 'مرفوض', hi: 'अस्वीकृत' },
  COMPLETE: { es: 'COMPLETADA', zh: '已完成', ja: '完了', de: 'ABGESCHLOSSEN', ru: 'ЗАВЕРШЕНО', it: 'COMPLETATA', fr: 'TERMINÉ', pt: 'CONCLUÍDA', ko: '완료', ar: 'مكتمل', hi: 'पूर्ण' },
  FAILED: { es: 'FALLIDA', zh: '失败', ja: '失敗', de: 'FEHLGESCHLAGEN', ru: 'НЕУДАЧА', it: 'FALLITA', fr: 'ÉCHOUÉ', pt: 'FALHOU', ko: '실패', ar: 'فشل', hi: 'विफल' },
  DRAFT: { es: 'BORRADOR', zh: '草稿', ja: '下書き', de: 'ENTWURF', ru: 'ЧЕРНОВИК', it: 'BOZZA', fr: 'BROUILLON', pt: 'RASCUNHO', ko: '초안', ar: 'مسودة', hi: 'मसौदा' },
  PREPARATION: { es: 'PREPARACIÓN', zh: '准备中', ja: '準備中', de: 'VORBEREITUNG', ru: 'ПОДГОТОВКА', it: 'PREPARAZIONE', fr: 'PRÉPARATION', pt: 'PREPARAÇÃO', ko: '준비', ar: 'التحضير', hi: 'तैयारी' },
  SUBMISSION: { es: 'ENVÍO', zh: '提交', ja: '提出', de: 'EINREICHUNG', ru: 'ПОДАЧА', it: 'INVIO', fr: 'SOUMISSION', pt: 'ENVIO', ko: '제출', ar: 'التقديم', hi: 'प्रस्तुति' },
  FILTERING: { es: 'FILTRADO', zh: '筛选', ja: 'フィルタリング', de: 'FILTERUNG', ru: 'ФИЛЬТРАЦИЯ', it: 'FILTRAGGIO', fr: 'FILTRAGE', pt: 'FILTRAGEM', ko: '필터링', ar: 'التصفية', hi: 'छंटाई' },
  DEBATE: { es: 'DEBATE', zh: '辩论', ja: '討論', de: 'DEBATTE', ru: 'ДЕБАТЫ', it: 'DIBATTITO', fr: 'DÉBAT', pt: 'DEBATE', ko: '토론', ar: 'نقاش', hi: 'बहस' },
  VOTE: { es: 'VOTACIÓN', zh: '投票', ja: '投票', de: 'ABSTIMMUNG', ru: 'ГОЛОСОВАНИЕ', it: 'VOTO', fr: 'VOTE', pt: 'VOTAÇÃO', ko: '투표', ar: 'تصويت', hi: 'मतदान' },
  DV: { es: 'VOTACIÓN', zh: '投票', ja: '投票', de: 'ABSTIMMUNG', ru: 'ГОЛОСОВАНИЕ', it: 'VOTO', fr: 'VOTE', pt: 'VOTAÇÃO', ko: '투표', ar: 'تصويت', hi: 'मतदान' },
  TALLY: { es: 'RECUENTO', zh: '计票', ja: '集計', de: 'AUSZÄHLUNG', ru: 'ПОДСЧЁТ', it: 'CONTEGGIO', fr: 'DÉCOMPTE', pt: 'APURAÇÃO', ko: '집계', ar: 'الفرز', hi: 'मतगणना' },
  FUNDING: { es: 'FINANCIACIÓN', zh: '资助', ja: '資金提供', de: 'FINANZIERUNG', ru: 'ФИНАНСИРОВАНИЕ', it: 'FINANZIAMENTO', fr: 'FINANCEMENT', pt: 'FINANCIAMENTO', ko: '자금 지원', ar: 'التمويل', hi: 'वित्तपोषण' },
  CLOSED: { es: 'CERRADA', zh: '已关闭', ja: '終了', de: 'GESCHLOSSEN', ru: 'ЗАКРЫТО', it: 'CHIUSA', fr: 'FERMÉ', pt: 'FECHADA', ko: '종료', ar: 'مغلق', hi: 'बंद' },

  // ---- Internal proposals: list filters ----
  All: { es: 'Todas', zh: '全部', ja: 'すべて', de: 'Alle', ru: 'Все', it: 'Tutte', fr: 'Toutes', pt: 'Todas', ko: '전체', ar: 'الكل', hi: 'सभी' },
  Active: { es: 'Activas', zh: '进行中', ja: 'アクティブ', de: 'Aktiv', ru: 'Активные', it: 'Attive', fr: 'Actives', pt: 'Ativas', ko: '진행 중', ar: 'نشطة', hi: 'सक्रिय' },
  Approved: { es: 'Aprobadas', zh: '已批准', ja: '承認済み', de: 'Genehmigt', ru: 'Одобренные', it: 'Approvate', fr: 'Approuvées', pt: 'Aprovadas', ko: '승인됨', ar: 'موافق عليها', hi: 'स्वीकृत' },
  Rejected: { es: 'Rechazadas', zh: '已拒绝', ja: '却下', de: 'Abgelehnt', ru: 'Отклонённые', it: 'Respinte', fr: 'Rejetées', pt: 'Rejeitadas', ko: '거부됨', ar: 'مرفوضة', hi: 'अस्वीकृत' },
  Draft: { es: 'Borrador', zh: '草稿', ja: '下書き', de: 'Entwurf', ru: 'Черновик', it: 'Bozza', fr: 'Brouillon', pt: 'Rascunho', ko: '초안', ar: 'مسودة', hi: 'मसौदा' },

  // ---- Internal proposals: list view ----
  'Board member election': { es: 'Elección de miembros de la junta', zh: '理事会成员选举', ja: '理事会メンバー選挙', de: 'Vorstandswahl', ru: 'Выборы членов совета', it: 'Elezione dei membri del consiglio', fr: 'Élection des membres du conseil', pt: 'Eleição de membros do conselho', ko: '이사회 구성원 선거', ar: 'انتخاب أعضاء المجلس', hi: 'बोर्ड सदस्य चुनाव' },
  'New election': { es: 'Nueva elección', zh: '新建选举', ja: '新しい選挙', de: 'Neue Wahl', ru: 'Новые выборы', it: 'Nuova elezione', fr: 'Nouvelle élection', pt: 'Nova eleição', ko: '새 선거', ar: 'انتخاب جديد', hi: 'नया चुनाव' },
  'New internal proposal': { es: 'Nueva propuesta interna', zh: '新建内部提案', ja: '新しい内部提案', de: 'Neuer interner Antrag', ru: 'Новое внутреннее предложение', it: 'Nuova proposta interna', fr: 'Nouvelle proposition interne', pt: 'Nova proposta interna', ko: '새 내부 제안', ar: 'مقترح داخلي جديد', hi: 'नया आंतरिक प्रस्ताव' },
  'DAO-governance decisions — process changes, parameter changes, polls. Not tied to a round; voting opens immediately.': { es: 'Decisiones de gobernanza de la DAO: cambios de proceso, cambios de parámetros, encuestas. No vinculadas a una ronda; la votación se abre de inmediato.', zh: 'DAO 治理决策——流程变更、参数变更、投票调查。不与轮次绑定；投票立即开放。', ja: 'DAO ガバナンスの決定 — プロセス変更、パラメータ変更、投票。ラウンドに紐づかず、投票はすぐに開始されます。', de: 'DAO-Governance-Entscheidungen – Prozessänderungen, Parameteränderungen, Umfragen. Nicht an eine Runde gebunden; die Abstimmung beginnt sofort.', ru: 'Решения по управлению DAO — изменения процессов, параметров, опросы. Не привязаны к раунду; голосование открывается сразу.', it: 'Decisioni di governance della DAO: modifiche ai processi, ai parametri, sondaggi. Non legate a un round; la votazione si apre subito.', fr: 'Décisions de gouvernance de la DAO — changements de processus, de paramètres, sondages. Non liées à un tour ; le vote ouvre immédiatement.', pt: 'Decisões de governança da DAO — mudanças de processo, de parâmetros, enquetes. Não vinculadas a uma rodada; a votação abre imediatamente.', ko: 'DAO 거버넌스 결정 — 프로세스 변경, 매개변수 변경, 설문. 라운드에 연결되지 않으며 투표가 즉시 시작됩니다.', ar: 'قرارات حوكمة الـ DAO — تغييرات في العمليات والمعايير واستطلاعات. غير مرتبطة بجولة؛ يبدأ التصويت فورًا.', hi: 'DAO-गवर्नेंस निर्णय — प्रक्रिया परिवर्तन, पैरामीटर परिवर्तन, पोल। किसी राउंड से बंधे नहीं; मतदान तुरंत शुरू होता है।' },
  'Propose a new 5-member board. Approval + the installation date trigger the platform to replace the board automatically.': { es: 'Propón una nueva junta de 5 miembros. La aprobación + la fecha de instalación hacen que la plataforma reemplace la junta automáticamente.', zh: '提议一个新的 5 人理事会。批准 + 安装日期将触发平台自动替换理事会。', ja: '新しい 5 人の理事会を提案します。承認 + 設置日になると、プラットフォームが自動的に理事会を置き換えます。', de: 'Schlagen Sie einen neuen 5-köpfigen Vorstand vor. Genehmigung + Installationsdatum lassen die Plattform den Vorstand automatisch ersetzen.', ru: 'Предложите новый совет из 5 человек. Одобрение + дата установки заставят платформу автоматически заменить совет.', it: 'Proponi un nuovo consiglio di 5 membri. L’approvazione + la data di installazione fanno sì che la piattaforma sostituisca automaticamente il consiglio.', fr: 'Proposez un nouveau conseil de 5 membres. L’approbation + la date d’installation déclenchent le remplacement automatique du conseil par la plateforme.', pt: 'Proponha um novo conselho de 5 membros. A aprovação + a data de instalação fazem a plataforma substituir o conselho automaticamente.', ko: '5명으로 구성된 새 이사회를 제안하세요. 승인 + 설치 날짜가 되면 플랫폼이 이사회를 자동으로 교체합니다.', ar: 'اقترح مجلسًا جديدًا من 5 أعضاء. الموافقة + تاريخ التنصيب يجعلان المنصة تستبدل المجلس تلقائيًا.', hi: 'एक नया 5-सदस्यीय बोर्ड प्रस्तावित करें। स्वीकृति + स्थापना तिथि पर प्लेटफ़ॉर्म स्वतः बोर्ड बदल देता है।' },
  'Search by proposal ID, title, or proposer…': { es: 'Buscar por ID de propuesta, título o proponente…', zh: '按提案 ID、标题或提案人搜索…', ja: '提案 ID、タイトル、または提案者で検索…', de: 'Nach Antrags-ID, Titel oder Einreicher suchen…', ru: 'Поиск по ID предложения, названию или автору…', it: 'Cerca per ID proposta, titolo o proponente…', fr: 'Rechercher par ID de proposition, titre ou proposant…', pt: 'Pesquisar por ID da proposta, título ou proponente…', ko: '제안 ID, 제목 또는 제안자로 검색…', ar: 'ابحث حسب معرّف المقترح أو العنوان أو مقدّمه…', hi: 'प्रस्ताव ID, शीर्षक या प्रस्तावक से खोजें…' },
  proposal: { es: 'propuesta', zh: '个提案', ja: '件の提案', de: 'Antrag', ru: 'предложение', it: 'proposta', fr: 'proposition', pt: 'proposta', ko: '제안', ar: 'مقترح', hi: 'प्रस्ताव' },
  proposals: { es: 'propuestas', zh: '个提案', ja: '件の提案', de: 'Anträge', ru: 'предложений', it: 'proposte', fr: 'propositions', pt: 'propostas', ko: '제안', ar: 'مقترحات', hi: 'प्रस्ताव' },
  'No proposals match the filter.': { es: 'Ninguna propuesta coincide con el filtro.', zh: '没有提案符合筛选条件。', ja: 'フィルターに一致する提案はありません。', de: 'Keine Anträge entsprechen dem Filter.', ru: 'Нет предложений, соответствующих фильтру.', it: 'Nessuna proposta corrisponde al filtro.', fr: 'Aucune proposition ne correspond au filtre.', pt: 'Nenhuma proposta corresponde ao filtro.', ko: '필터와 일치하는 제안이 없습니다.', ar: 'لا توجد مقترحات تطابق عامل التصفية.', hi: 'फ़िल्टर से मेल खाने वाला कोई प्रस्ताव नहीं।' },
  'No board-member elections yet.': { es: 'Aún no hay elecciones de miembros de la junta.', zh: '暂无理事会成员选举。', ja: '理事会メンバー選挙はまだありません。', de: 'Noch keine Vorstandswahlen.', ru: 'Выборов членов совета пока нет.', it: 'Ancora nessuna elezione dei membri del consiglio.', fr: "Aucune élection de membres du conseil pour l'instant.", pt: 'Ainda não há eleições de membros do conselho.', ko: '아직 이사회 구성원 선거가 없습니다.', ar: 'لا توجد انتخابات لأعضاء المجلس بعد.', hi: 'अभी तक कोई बोर्ड-सदस्य चुनाव नहीं।' },
  'No internal proposals yet.': { es: 'Aún no hay propuestas internas.', zh: '暂无内部提案。', ja: '内部提案はまだありません。', de: 'Noch keine internen Anträge.', ru: 'Внутренних предложений пока нет.', it: 'Ancora nessuna proposta interna.', fr: "Aucune proposition interne pour l'instant.", pt: 'Ainda não há propostas internas.', ko: '아직 내부 제안이 없습니다.', ar: 'لا توجد مقترحات داخلية بعد.', hi: 'अभी तक कोई आंतरिक प्रस्ताव नहीं।' },

  // ---- Internal proposals: type / scope / voting-power labels ----
  'Instructive (names actors to act)': { es: 'Instructiva (designa a quién debe actuar)', zh: '指令型（指定执行者）', ja: '指示型（実行する主体を指名）', de: 'Anweisend (benennt handelnde Akteure)', ru: 'Директивное (назначает исполнителей)', it: 'Istruttiva (nomina chi deve agire)', fr: 'Instructive (désigne les acteurs à agir)', pt: 'Instrutiva (nomeia quem deve agir)', ko: '지시형 (실행 주체 지정)', ar: 'توجيهية (تحدد الجهات المنفّذة)', hi: 'निर्देशात्मक (कार्य करने वालों को नामित करता है)' },
  'Informative (yes / no decision)': { es: 'Informativa (decisión sí / no)', zh: '信息型（是/否决定）', ja: '情報型（賛成／反対の決定）', de: 'Informativ (Ja-/Nein-Entscheidung)', ru: 'Информационное (решение да/нет)', it: 'Informativa (decisione sì / no)', fr: 'Informative (décision oui / non)', pt: 'Informativa (decisão sim / não)', ko: '정보형 (찬반 결정)', ar: 'معلوماتية (قرار نعم / لا)', hi: 'सूचनात्मक (हाँ / नहीं निर्णय)' },
  'Poll (choose option(s))': { es: 'Encuesta (elige opción(es))', zh: '投票调查（选择选项）', ja: '投票（選択肢を選ぶ）', de: 'Umfrage (Option(en) wählen)', ru: 'Опрос (выбор варианта(ов))', it: 'Sondaggio (scegli opzione/i)', fr: 'Sondage (choisir option(s))', pt: 'Enquete (escolher opção(ões))', ko: '설문 (옵션 선택)', ar: 'استطلاع (اختر خيارًا أو أكثر)', hi: 'पोल (विकल्प चुनें)' },
  'Spending (treasury payment on approval)': { es: 'Gasto (pago de tesorería al aprobarse)', zh: '支出（批准后从金库付款）', ja: '支出（承認時にトレジャリーから支払い）', de: 'Ausgabe (Treasury-Zahlung bei Genehmigung)', ru: 'Расход (выплата из казначейства при одобрении)', it: 'Spesa (pagamento dalla tesoreria all’approvazione)', fr: "Dépense (paiement de la trésorerie à l'approbation)", pt: 'Gasto (pagamento da tesouraria na aprovação)', ko: '지출 (승인 시 재무 지급)', ar: 'إنفاق (دفع من الخزينة عند الموافقة)', hi: 'व्यय (स्वीकृति पर कोष से भुगतान)' },
  'Non-board DReps only': { es: 'Solo DReps que no son de la junta', zh: '仅限非理事会 DRep', ja: '理事会以外の DRep のみ', de: 'Nur Nicht-Vorstands-DReps', ru: 'Только DRep вне совета', it: 'Solo DRep non del consiglio', fr: 'DReps hors conseil uniquement', pt: 'Apenas DReps fora do conselho', ko: '비이사회 DRep만', ar: 'مندوبو DRep من غير المجلس فقط', hi: 'केवल गैर-बोर्ड DRep' },
  'Board members only': { es: 'Solo miembros de la junta', zh: '仅限理事会成员', ja: '理事会メンバーのみ', de: 'Nur Vorstandsmitglieder', ru: 'Только члены совета', it: 'Solo membri del consiglio', fr: 'Membres du conseil uniquement', pt: 'Apenas membros do conselho', ko: '이사회 구성원만', ar: 'أعضاء المجلس فقط', hi: 'केवल बोर्ड सदस्य' },
  'All DReps (board + others)': { es: 'Todos los DReps (junta + otros)', zh: '所有 DRep（理事会 + 其他）', ja: 'すべての DRep（理事会 + その他）', de: 'Alle DReps (Vorstand + andere)', ru: 'Все DRep (совет + остальные)', it: 'Tutti i DRep (consiglio + altri)', fr: 'Tous les DReps (conseil + autres)', pt: 'Todos os DReps (conselho + outros)', ko: '모든 DRep (이사회 + 기타)', ar: 'كل مندوبي DRep (المجلس + غيرهم)', hi: 'सभी DRep (बोर्ड + अन्य)' },
  '1 member = 1 vote': { es: '1 miembro = 1 voto', zh: '1 名成员 = 1 票', ja: '1 メンバー = 1 票', de: '1 Mitglied = 1 Stimme', ru: '1 участник = 1 голос', it: '1 membro = 1 voto', fr: '1 membre = 1 voix', pt: '1 membro = 1 voto', ko: '1인 = 1표', ar: 'عضو واحد = صوت واحد', hi: '1 सदस्य = 1 वोट' },
  'Adjusted voting power': { es: 'Poder de voto ajustado', zh: '调整后的投票权', ja: '調整後の投票力', de: 'Angepasste Stimmkraft', ru: 'Скорректированная сила голоса', it: 'Potere di voto rettificato', fr: 'Pouvoir de vote ajusté', pt: 'Poder de voto ajustado', ko: '조정된 투표력', ar: 'قوة تصويت معدّلة', hi: 'समायोजित मतदान शक्ति' },
  'On-chain (unadjusted) voting power': { es: 'Poder de voto on-chain (sin ajustar)', zh: '链上（未调整）投票权', ja: 'オンチェーン（未調整）の投票力', de: 'On-Chain-Stimmkraft (unangepasst)', ru: 'Ончейн (нескорректированная) сила голоса', it: 'Potere di voto on-chain (non rettificato)', fr: 'Pouvoir de vote on-chain (non ajusté)', pt: 'Poder de voto on-chain (não ajustado)', ko: '온체인 (미조정) 투표력', ar: 'قوة التصويت على السلسلة (غير معدّلة)', hi: 'ऑन-चेन (असमायोजित) मतदान शक्ति' },
  threshold: { es: 'umbral', zh: '阈值', ja: 'しきい値', de: 'Schwelle', ru: 'порог', it: 'soglia', fr: 'seuil', pt: 'limiar', ko: '임계값', ar: 'العتبة', hi: 'सीमा' },
  by: { es: 'por', zh: '提交者', ja: '提案者', de: 'von', ru: 'автор', it: 'di', fr: 'par', pt: 'por', ko: '작성자', ar: 'بواسطة', hi: 'द्वारा' },
  ends: { es: 'finaliza', zh: '结束于', ja: '終了', de: 'endet', ru: 'до', it: 'termina', fr: 'se termine', pt: 'termina', ko: '종료', ar: 'ينتهي', hi: 'समाप्त' },

  // ---- Pager + vote chip ----
  Previous: { es: 'Anterior', zh: '上一页', ja: '前へ', de: 'Zurück', ru: 'Назад', it: 'Precedente', fr: 'Précédent', pt: 'Anterior', ko: '이전', ar: 'السابق', hi: 'पिछला' },
  Next: { es: 'Siguiente', zh: '下一页', ja: '次へ', de: 'Weiter', ru: 'Далее', it: 'Successivo', fr: 'Suivant', pt: 'Próximo', ko: '다음', ar: 'التالي', hi: 'अगला' },
  Page: { es: 'Página', zh: '第', ja: 'ページ', de: 'Seite', ru: 'Страница', it: 'Pagina', fr: 'Page', pt: 'Página', ko: '페이지', ar: 'صفحة', hi: 'पृष्ठ' },
  of: { es: 'de', zh: '页，共', ja: '/', de: 'von', ru: 'из', it: 'di', fr: 'sur', pt: 'de', ko: '/', ar: 'من', hi: 'का' },
  'you voted': { es: 'votaste', zh: '你投了', ja: '投票', de: 'gestimmt', ru: 'голос', it: 'votato', fr: 'voté', pt: 'votou', ko: '투표', ar: 'صوتت', hi: 'मत' },
  'you abstained': { es: 'te abstuviste', zh: '你已弃权', ja: '棄権しました', de: 'enthalten', ru: 'воздержались', it: 'astenuto', fr: 'abstenu', pt: 'absteve-se', ko: '기권함', ar: 'امتنعت', hi: 'अनुपस्थित रहे' },
  'you chose': { es: 'elegiste', zh: '你选择了', ja: '選択', de: 'gewählt', ru: 'выбрано', it: 'scelto', fr: 'choisi', pt: 'escolheu', ko: '선택함', ar: 'اخترت', hi: 'चुना' },
  YES: { es: 'SÍ', zh: '赞成', ja: '賛成', de: 'JA', ru: 'ДА', it: 'SÌ', fr: 'OUI', pt: 'SIM', ko: '찬성', ar: 'نعم', hi: 'हाँ' },
  NO: { es: 'NO', zh: '反对', ja: '反対', de: 'NEIN', ru: 'НЕТ', it: 'NO', fr: 'NON', pt: 'NÃO', ko: '반대', ar: 'لا', hi: 'नहीं' },
  Abstain: { es: 'Abstención', zh: '弃权', ja: '棄権', de: 'Enthaltung', ru: 'Воздержаться', it: 'Astenersi', fr: 'Abstention', pt: 'Abstenção', ko: '기권', ar: 'امتناع', hi: 'अनुपस्थित' },
};

/** Translate an English source string into `lang`, falling back to the English text. */
export function translate(lang: LangCode, key: string): string {
  if (lang === 'en') return key;
  return T[key]?.[lang] ?? key;
}
